In [1]:
import numpy as np

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [3]:
data = pd.read_csv('../artifacts/sentiment_analysis.csv')

In [4]:
data.head()

   id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

Data Preprocessing

In [5]:
data.shape

(7920, 3)

In [8]:
data.duplicated().sum()

np.int64(0)

##Text Preprocessing##

In [9]:
import re
import string

convert uppercase to lowercase

In [10]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [11]:
data["tweet"].head(5)

0    #fingerprint #pregnancy test https://goo.gl/h1...
1    finally a transparant silicon case ^^ thanks t...
2    we love this! would you go? #talk #makememorie...
3    i'm wired i know i'm george i was made that wa...
4    what amazing service! apple won't even talk to...
Name: tweet, dtype: str

Remove Links

In [12]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(re.sub(r'^https?:\/\/.*[\r\n]*','',x,flags=re.MULTILINE) for x in x.split()))

In [13]:
data["tweet"].head(5)

0    #fingerprint #pregnancy test  #android #apps #...
1    finally a transparant silicon case ^^ thanks t...
2    we love this! would you go? #talk #makememorie...
3    i'm wired i know i'm george i was made that wa...
4    what amazing service! apple won't even talk to...
Name: tweet, dtype: str

Remove Puncuations

In [14]:
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation,'')
    return text

data["tweet"] = data["tweet"].apply(remove_punctuations)

In [15]:
data["tweet"].head(5)

0    fingerprint pregnancy test  android apps beaut...
1    finally a transparant silicon case  thanks to ...
2    we love this would you go talk makememories un...
3    im wired i know im george i was made that way ...
4    what amazing service apple wont even talk to m...
Name: tweet, dtype: str

In [16]:
data["tweet"].tail(5)

7915    live out loud lol liveoutloud selfie smile son...
7916    we would like to wish you an amazing day make ...
7917    helping my lovely 90 year old neighbor with he...
7918    finally got my smart pocket wifi stay connecte...
7919    apple barcelona apple store bcn barcelona trav...
Name: tweet, dtype: str

Remove numbers

In [19]:
data["tweet"] = data["tweet"].str.replace("[0-9]+",'',regex=True)

In [20]:
data["tweet"].tail(5)

7915    live out loud lol liveoutloud selfie smile son...
7916    we would like to wish you an amazing day make ...
7917    helping my lovely  year old neighbor with her ...
7918    finally got my smart pocket wifi stay connecte...
7919    apple barcelona apple store bcn barcelona trav...
Name: tweet, dtype: str

Remove stopwords

In [21]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.3-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.2.28-cp312-cp312-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.3-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.5 MB 598.5 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.5 MB 598.5 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.5 MB 598.5 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.5 MB 598.5 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.5 MB 598.5 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.5 MB 598.5 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.5 MB 598.5 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.5 MB 256.1 kB/s eta 0:00:03
   -------------------- ------------------- 0.8/1.5 MB 256.1 kB/s eta 0:00:03
   --------------------------- ------------ 1.0/1.5 MB 324.7 kB/s eta 0:00:02
   --------------------------- ------------ 1.0/1.5 MB 324.7 kB/s eta 0:00:02
   ---------------------------------- ----- 1.3/1.5 MB 379.1 kB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 400.1 kB/s  0:00:03
Downloading regex-2026.2.28-cp312-cp312-win_amd64.whl (277 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Installing collected packages: regex, joblib, click, nltk

   ---------------------------------------- 0/4 [regex]
   ---------------------------------------- 0/4 [regex]
   ---------------------------------------- 0/4 [regex]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ---------------------------------------- 4/4 [nltk]

Successfully installed click-8.3.1 joblib-1.5.3 nltk-3.9.3 regex-2026.2.28

In [22]:
import nltk

In [24]:
nltk.download('stopwords',download_dir='../static/model')

[nltk_data] Downloading package stopwords to ../static/model...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [26]:
with open('../static/model/corpora/stopwords/english','r') as file:
    sw = file.read().splitlines()

In [27]:
sw

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [28]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(x for x in x.split() if x not in sw))

In [29]:
data["tweet"].head(5)

0    fingerprint pregnancy test android apps beauti...
1    finally transparant silicon case thanks uncle ...
2    love would go talk makememories unplug relax i...
3    im wired know im george made way iphone cute d...
4    amazing service apple wont even talk question ...
Name: tweet, dtype: str

Stemming

In [31]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [32]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(ps.stem(x) for x in x.split()))

In [33]:
data["tweet"].head(5)

0    fingerprint pregnanc test android app beauti c...
1    final transpar silicon case thank uncl yay son...
2    love would go talk makememori unplug relax iph...
3    im wire know im georg made way iphon cute dave...
4    amaz servic appl wont even talk question unles...
Name: tweet, dtype: str

##Full dataset without uppercase letters, links, numbers, stopwords, and stemming(the base format of a word - ex:- watches>>watch, finally>>final)##

In [34]:
data

        id  label                                              tweet
0        1      0  fingerprint pregnanc test android app beauti c...
1        2      0  final transpar silicon case thank uncl yay son...
2        3      0  love would go talk makememori unplug relax iph...
3        4      0  im wire know im georg made way iphon cute dave...
4        5      1  amaz servic appl wont even talk question unles...
...    ...    ...                                                ...
7915  7916      0  live loud lol liveoutloud selfi smile soni mus...
7916  7917      0  would like wish amaz day make everi minut coun...
7917  7918      0  help love year old neighbor ipad morn made rea...
7918  7919      0  final got smart pocket wifi stay connect anyti...
7919  7920      0  appl barcelona appl store bcn barcelona travel...

[7920 rows x 3 columns]

##Vocabulary building##
##each word in the sentences in tweet one by one get as the vocabulary and using that can arrange that tweets as vector characters##

In [40]:
from collections import Counter
vocab1 = Counter()

In [41]:
vocab1

Counter()

In [47]:
for sentence in data['tweet']:
    vocab1.update(sentence.split())

In [48]:
vocab1

Counter({'iphon': 4073,
         'appl': 2876,
         'samsung': 1395,
         'new': 1137,
         'phone': 1015,
         'follow': 885,
         'soni': 819,
         '…': 751,
         'ipad': 537,
         'rt': 525,
         'love': 499,
         'like': 455,
         'day': 426,
         'app': 416,
         'life': 415,
         'android': 414,
         'photo': 394,
         'get': 382,
         'io': 382,
         'galaxi': 361,
         'instagram': 358,
         'case': 348,
         'beauti': 322,
         'cute': 322,
         'gain': 311,
         'today': 309,
         'work': 306,
         'im': 294,
         'back': 294,
         'fuck': 293,
         'happi': 293,
         'photographi': 292,
         'game': 282,
         'got': 280,
         'fun': 277,
         'news': 265,
         'thank': 263,
         'music': 263,
         'time': 248,
         'make': 247,
         'updat': 236,
         'smile': 231,
         'instagood': 226,
         'funni': 223,
         'one': 221,
         'girl': 220,
         'lol': 215,
         'fashion': 215,
         'itun': 212,
         'ipod': 211,
         'go': 209,
         'birthday': 206,
         'tech': 205,
         'iphonex': 199,
         'ps': 198,
         'final': 192,
         'photooftheday': 191,
         'friend': 191,
         'everyon': 189,
         'cant': 180,
         'good': 180,
         'amaz': 178,
         'use': 174,
         'look': 171,
         'fail': 169,
         'dont': 168,
         'must': 168,
         'note': 166,
         'want': 165,
         'sougofollow': 165,
         'selfi': 164,
         'mac': 164,
         'gift': 163,
         'sale': 156,
         'hate': 155,
         'free': 149,
         'babi': 148,
         'would': 146,
         'iger': 143,
         'home': 143,
         'year': 141,
         'camera': 139,
         'famili': 139,
         'need': 138,
         'iphonesia': 137,
         'best': 136,
         'smartphon': 134,
         'cool': 134,
         'art': 132,
         'iphoneonli': 129,
         'charger': 128,
         'everi': 127,
         'color': 125,
         'suck': 125,
         'live': 124,
         'christma': 124,
         'buy': 124,
         'tri': 122,
         'health': 120,
         'summer': 119,
         'picoftheday': 117,
         'product': 117,
         'thing': 116,
         'shop': 115,
         'white': 115,
         'hour': 113,
         'u': 113,
         'still': 112,
         'mobil': 111,
         'minut': 111,
         'much': 109,
         'say': 109,
         'even': 108,
         'natur': 107,
         'night': 107,
         'awesom': 107,
         'know': 106,
         'come': 105,
         'macbook': 105,
         'window': 104,
         'money': 103,
         'screen': 102,
         'ff': 102,
         'laptop': 102,
         'download': 101,
         'ever': 101,
         'great': 98,
         'excit': 98,
         'wish': 97,
         'sexi': 94,
         'wait': 94,
         'take': 94,
         'motorola': 94,
         'delet': 93,
         'style': 93,
         'accessori': 93,
         'store': 91,
         'black': 90,
         'instamood': 90,
         'retweet': 90,
         'comput': 89,
         'last': 89,
         'followm': 89,
         'technolog': 88,
         'wont': 87,
         'nice': 87,
         'pink': 86,
         'iphone…': 86,
         'twitter': 86,
         'keep': 85,
         'sweet': 85,
         'peopl': 85,
         'realli': 83,
         'ive': 83,
         'guy': 83,
         'pictur': 82,
         'morn': 82,
         'charg': 81,
         'watch': 81,
         'video': 81,
         'travel': 81,
         'never': 81,
         'first': 81,
         'us': 80,
         'batteri': 80,
         'think': 80,
         'right': 80,
         'old': 80,
         'fix': 80,
         'via': 79,
         'boy': 77,
         'play': 77,
         'custom': 77,
         'give': 76,
         'googl': 76,
         'playstat': 76,
         'job': 75,
         'fuckyou': 75,
         'everyth': 75,
         'kid': 74,
         'hey': 73,
         'let': 73,
         'tv': 73,
         'toy': 73,
         'made': 72,
         'pretti': 72,
         'well': 72,
         'upgrad': 72,
         'anoth': 71,
         'dog': 71,
         'feel': 71,
         'cover': 71,
         'pic': 70,
         'see': 70,
         'blue': 70,
         'yay': 69,
         'week': 69,
         'red': 69,
         'doesnt': 69,
         'count': 69,
         'stupid': 68,
         'start': 68,
         'text': 68,
         'present': 68,
         'world': 68,
         'offer': 68,
         'gadget': 68,
         'x': 68,
         'sun': 67,
         'instadaili': 66,
         'check': 66,
         'quot': 65,
         'nokia': 65,
         'headphon': 65,
         'big': 64,
         'design': 64,
         'food': 64,
         'deal': 64,
         'alway': 63,
         'appstor': 63,
         'friday': 63,
         'date': 63,
         'youtub': 62,
         'book': 62,
         'tl': 62,
         'rhyme': 62,
         'amazon': 61,
         'sunset': 61,
         'tablet': 61,
         'cat': 61,
         'pc': 61,
         'xperia': 60,
         'song': 60,
         'laugh': 59,
         'blackberri': 58,
         'capetown': 58,
         'ig': 58,
         'hello': 58,
         'bought': 57,
         'sunday': 57,
         'imag': 57,
         'sky': 56,
         'holiday': 56,
         'lost': 56,
         'sinc': 56,
         'wow': 56,
         'top': 56,
         'better': 56,
         'instap': 55,
         'flower': 55,
         'month': 55,
         'hot': 55,
         'surf': 55,
         'followback': 54,
         'oh': 54,
         'gamer': 54,
         'gb': 54,
         'facebook': 54,
         'way': 53,
         'share': 53,
         'green': 53,
         'put': 53,
         'capetownsup': 53,
         'sup': 53,
         'mine': 53,
         'phonecas': 53,
         'iphoneographi': 52,
         'gold': 52,
         'g': 52,
         'valentin': 52,
         'miss': 52,
         'ye': 52,
         'heart': 52,
         'weekend': 52,
         'servic': 51,
         'newyear': 51,
         'face': 51,
         'th': 51,
         'help': 51,
         'wifi': 50,
         'tweegram': 50,
         'twitch': 50,
         'moment': 50,
         'call': 50,
         'beach': 50,
         'macbookpro': 50,
         'find': 50,
         'god': 50,
         'hard': 49,
         'hateappl': 49,
         'iphoneplu': 49,
         'chang': 49,
         'dear': 48,
         'parti': 48,
         'pleas': 48,
         'pay': 47,
         'support': 47,
         'arriv': 47,
         'enjoy': 47,
         'didnt': 47,
         'yeah': 47,
         'user': 46,
         'ya': 46,
         'littl': 46,
         'stop': 46,
         'pro': 46,
         'show': 46,
         'restor': 46,
         'listen': 45,
         'that': 45,
         'problem': 45,
         'siri': 45,
         'power': 45,
         'run': 44,
         'came': 44,
         'word': 44,
         'swag': 44,
         'welcom': 44,
         'two': 44,
         'could': 44,
         'man': 44,
         'newphon': 44,
         'messag': 44,
         'light': 43,
         'win': 43,
         'blog': 43,
         'turn': 43,
         'tweet': 43,
         'likelik': 43,
         'may': 43,
         'fit': 43,
         'plu': 43,
         'lock': 43,
         'order': 43,
         'microsoft': 43,
         'busi': 42,
         'id': 42,
         'devic': 42,
         'usa': 42,
         'car': 42,
         'took': 42,
         'avail': 42,
         'sonyphoto': 42,
         'switch': 42,
         'gonna': 42,
         'hair': 42,
         'att': 42,
         'relax': 41,
         'crazi': 41,
         'reason': 41,
         'random': 41,
         'alreadi': 41,
         'nofilt': 41,
         'oneplu': 41,
         'insta': 41,
         'vsco': 41,
         'discount': 41,
         '•': 41,
         'cabl': 40,
         'saturday': 40,
         'joy': 40,
         'model': 40,
         'piss': 40,
         'hope': 40,
         'serious': 39,
         'replac': 39,
         'tab': 39,
         'w': 39,
         'readi': 39,
         'bestpric': 39,
         'bless': 39,
         'tell': 39,
         'coupl': 39,
         'die': 39,
         'done': 38,
         'movi': 38,
         'broken': 38,
         'compani': 38,
         'annoy': 38,
         'photograph': 38,
         'p': 38,
         'haha': 38,
         'tbt': 38,
         'crash': 37,
         'coffe': 37,
         'imessag': 37,
         'contact': 37,
         'shit': 37,
         'trip': 37,
         'piec': 37,
         'monday': 36,
         'bad': 36,
         'yet': 36,
         'mom': 36,
         'sync': 36,
         'enough': 36,
         'gay': 36,
         'iphonecas': 36,
         'break': 36,
         'hous': 36,
         'noth': 35,
         'tree': 35,
         'peac': 35,
         'stuff': 35,
         '—': 35,
         'ago': 35,
         'drop': 34,
         'complet': 34,
         'taken': 34,
         'earli': 34,
         'mani': 34,
         'fan': 34,
         'actual': 34,
         'sleep': 34,
         'long': 34,
         'soon': 34,
         'password': 34,
         'next': 34,
         'verizon': 34,
         'anyon': 34,
         'number': 34,
         'fresh': 34,
         'code': 34,
         'decid': 34,
         'samsunggalaxi': 33,
         'sister': 33,
         'spring': 33,
         'send': 33,
         'real': 33,
         'unlock': 33,
         'emoji': 33,
         'care': 33,
         'favorit': 33,
         'happen': 33,
         'mini': 33,
         'someon': 32,
         'instago': 32,
         'chill': 32,
         'teamfollowback': 32,
         'someth': 32,
         'featur': 32,
         'galaxynot': 32,
         'colleg': 32,
         'sad': 32,
         'k': 32,
         'worst': 32,
         'market': 31,
         'set': 31,
         'end': 31,
         'singl': 31,
         'portrait': 31,
         'husband': 31,
         'fast': 31,
         'geek': 31,
         'steemit': 31,
         'london': 31,
         'sony…': 31,
         'anyth': 31,
         'water': 30,
         'email': 30,
         'cloud': 30,
         'followsunday': 30,
         'perfect': 30,
         'nyc': 30,
         'learn': 30,
         'healthi': 30,
         'gratitud': 30,
         'decor': 30,
         'steve': 30,
         'ill': 30,
         'releas': 30,
         'brand': 30,
         'softwar': 29,
         'button': 29,
         'broke': 29,
         'xbox': 29,
         'school': 29,
         'wonder': 29,
         'fruit': 29,
         'kindl': 29,
         'air': 29,
         'sonylen': 29,
         'sonyphotographi': 29,
         'sound': 29,
         'kiss': 29,
         'anim': 29,
         'c': 28,
         'wed': 28,
         'z': 28,
         'drink': 28,
         'tomorrow': 28,
         'dad': 28,
         'beat': 28,
         'puppi': 28,
         'gone': 28,
         'thailand': 28,
         'sure': 28,
         'talk': 27,
         'connect': 27,
         'bestfriend': 27,
         'pop': 27,
         'card': 27,
         'ad': 27,
         'version': 27,
         'popular': 27,
         'os': 27,
         'stori': 27,
         'dream': 27,
         'cellphon': 27,
         'florida': 27,
         'lg': 27,
         'without': 27,
         'crap': 27,
         'андроид': 27,
         'map': 27,
         'inspir': 27,
         'cake': 27,
         'instalov': 27,
         'also': 27,
         'said': 27,
         'flash': 27,
         'crack': 27,
         'ok': 27,
         'relationship': 27,
         'pet': 26,
         'brother': 26,
         'daughter': 26,
         'b': 26,
         'read': 26,
         'smart': 26,
         'imac': 26,
         'itali': 26,
         'away': 26,
         'ebay': 26,
         'igdaili': 26,
         'ugh': 26,
         'instalik': 26,
         'ask': 26,
         'ilc': 26,
         'pm': 26,
         'uk': 25,
         'eye': 25,
         'film': 25,
         'less': 25,
         'memori': 25,
         'gear': 25,
         'whole': 25,
         'garden': 25,
         'super': 25,
         'luxuri': 25,
         'vocat': 25,
         'khaoko': 25,
         'htc': 25,
         'psn': 25,
         'post': 25,
         'isnt': 25,
         'purchas': 24,
         'pie': 24,
         'wallpap': 24,
         'instahub': 24,
         'differ': 24,
         'newyork': 24,
         'shoot': 24,
         '–': 24,
         'lifestyl': 24,
         'hand': 24,
         'instagood…': 24,
         'jj': 24,
         'there': 24,
         'citi': 24,
         'instal': 24,
         'unitedst': 24,
         'guitarplay': 24,
         'mother': 24,
         'india': 24,
         'japan': 24,
         'yesterday': 24,
         'rain': 24,
         'applewatch': 24,
         'save': 24,
         'idea': 24,
         'leav': 24,
         'mirror': 24,
         'line': 24,
         'entrepreneur': 24,
         'xperiaz': 23,
         'inch': 23,
         'kill': 23,
         'blackandwhit': 23,
         'instacool': 23,
         '£': 23,
         'sport': 23,
         'rock': 23,
         'price': 23,
         'full': 23,
         'bestoftheday': 23,
         'shotoniphon': 23,
         'though': 23,
         'makeup': 23,
         'addict': 23,
         'samsung…': 23,
         'edit': 23,
         'total': 23,
         'photofe': 23,
         'reallyr': 23,
         'ador': 23,
         'woman': 23,
         'charm': 23,
         'tshirt': 23,
         'wtf': 23,
         'snapspeed…': 23,
         'lot': 23,
         'click': 23,
         'e': 23,
         'fact': 22,
         'goe': 22,
         'receiv': 22,
         'person': 22,
         'keyboard': 22,
         'usb': 22,
         'icloud': 22,
         'small': 22,
         'orang': 22,
         'true': 22,
         'jun': 22,
         'caus': 22,
         'nike': 22,
         'r': 22,
         'went': 22,
         'proud': 22,
         'exquisit': 22,
         'squishi': 22,
         'strap': 22,
         'human': 22,
         'ly': 22,
         'tonight': 22,
         'danc': 22,
         'facetim': 22,
         'lose': 21,
         'ootd': 21,
         'bit': 21,
         'thought': 21,
         'repair': 21,
         'liter': 21,
         'tattoo': 21,
         'chocol': 21,
         'might': 21,
         'bring': 21,
         'boyfriend': 21,
         'almost': 21,
         'repost': 21,
         'dj': 21,
         'tuesday': 21,
         'forev': 21,
         'togeth': 21,
         'street': 21,
         'likeforlik': 20,
         'dead': 20,
         'truth': 20,
         'ur': 20,
         'hashtag': 20,
         'ipadmini': 20,
         'magic': 20,
         'tmobil': 20,
         'ship': 20,
         'open': 20,
         'prophet': 20,
         'sick': 20,
         'account': 20,
         'drive': 20,
         'len': 20,
         'feed': 20,
         'your': 20,
         'els': 20,
         'load': 20,
         'link': 20,
         'videogam': 20,
         'data': 20,
         'redbubbl': 20,
         'what': 20,
         'slow': 20,
         'eat': 20,
         'thankyou': 20,
         'latest': 20,
         'consol': 20,
         'believ': 20,
         'xma': 20,
         'bore': 20,
         'daddi': 20,
         'type': 19,
         'mess': 19,
         'havent': 19,
         'touch': 19,
         'freak': 19,
         'creativ': 19,
         'it’': 19,
         'wrong': 19,
         'poem': 19,
         'n': 19,
         'min': 19,
         'second': 19,
         'fall': 19,
         'past': 19,
         'half': 19,
         'simpl': 19,
         'mm': 19,
         'visit': 19,
         'goodnight': 19,
         'pick': 19,
         'april': 19,
         'futur': 19,
         'shitti': 19,
         'tag': 19,
         'mean': 19,
         'room': 19,
         'men': 19,
         'skin': 19,
         'artist': 19,
         'winter': 19,
         'foodporn': 19,
         'guess': 19,
         'canon': 19,
         'yummi': 19,
         'photobooth': 19,
         'patent': 18,
         'cut': 18,
         'indonesia': 18,
         'sorri': 18,
         'issu': 18,
         'box': 18,
         'bug': 18,
         'fml': 18,
         'offici': 18,
         'sonyalpha': 18,
         'high': 18,
         'calendar': 18,
         'team': 18,
         'roll': 18,
         'experi': 18,
         'edg': 18,
         'hd': 18,
         'uniqu': 18,
         'mind': 18,
         'miami': 18,
         'glad': 18,
         'sea': 18,
         'stay': 18,
         'trend': 18,
         'soror': 18,
         'move': 18,
         'wall': 17,
         'daili': 17,
         'vlog': 17,
         'stand': 17,
         'blackfriday': 17,
         'reset': 17,
         'special': 17,
         'mood': 17,
         'vaio': 17,
         'throw': 17,
         'passion': 17,
         'sprint': 17,
         'space': 17,
         'hold': 17,
         'freez': 17,
         'mad': 17,
         'purpos': 17,
         'delici': 17,
         'far': 17,
         'al': 17,
         'june': 17,
         'canada': 17,
         'sent': 17,
         'captur': 17,
         'march': 17,
         'wipe': 17,
         'wast': 17,
         'zeeland': 17,
         'nikon': 17,
         'applesuck': 17,
         'king': 17,
         'trump': 17,
         'california': 17,
         'surpris': 17,
         'protect': 17,
         'novemb': 17,
         'adventur': 17,
         'digit': 17,
         'internet': 17,
         'stream': 17,
         'rose': 17,
         'develop': 17,
         'outdoor': 16,
         'creat': 16,
         'landscap': 16,
         'bright': 16,
         'origin': 16,
         'soul': 16,
         'abl': 16,
         'earphon': 16,
         'banana': 16,
         'spend': 16,
         'stevejob': 16,
         'least': 16,
         'draw': 16,
         'ny': 16,
         'angri': 16,
         'bird': 16,
         'gorgeou': 16,
         'dress': 16,
         'manag': 16,
         'wanna': 16,
         'europ': 16,
         'fish': 16,
         'hateiphon': 16,
         'inlov': 16,
         'lte': 16,
         'storag': 16,
         'blond': 16,
         'meet': 16,
         'motiv': 16,
         'sunni': 16,
         'left': 16,
         'walk': 16,
         'v': 16,
         'onlin': 16,
         'fb': 16,
         'colour': 16,
         'hack': 16,
         'snow': 16,
         'join': 16,
         'seem': 15,
         'goal': 15,
         'produc': 15,
         'program': 15,
         'univers': 15,
         'yum': 15,
         'shot': 15,
         'children': 15,
         'uae': 15,
         'purpl': 15,
         'mommi': 15,
         'sell': 15,
         'pari': 15,
         'silver': 15,
         'provid': 15,
         'track': 15,
         'photoshoot': 15,
         'newtoy': 15,
         'gener': 15,
         'screw': 15,
         'cook': 15,
         'bye': 15,
         'wireless': 15,
         'part': 15,
         'gotta': 15,
         'explor': 15,
         'followfollow': 15,
         'f': 15,
         'found': 15,
         'longer': 15,
         'celebr': 15,
         'gave': 15,
         'plan': 15,
         'vintag': 15,
         'later': 15,
         'januari': 15,
         'apple…': 15,
         'gs': 15,
         'question': 14,
         'wife': 14,
         'subscrib': 14,
         'america': 14,
         'bday': 14,
         'bull': 14,
         'ladi': 14,
         'droid': 14,
         'iphonephotographi': 14,
         'singer': 14,
         'i’m': 14,
         'qualiti': 14,
         'mode': 14,
         'park': 14,
         'rid': 14,
         'level': 14,
         'babe': 14,
         'cold': 14,
         'cri': 14,
         'display': 14,
         'okay': 14,
         'valentinesday': 14,
         'februari': 14,
         'hi': 14,
         'instaphoto': 14,
         'middl': 14,
         'info': 14,
         'playlist': 14,
         'bot': 14,
         'event': 14,

In [49]:
len(vocab1)

15949

In [45]:
data.shape

(7920, 3)

There have 15949 features. when we vectorization we have to read 15949 for each row. so we narrowdown the vacabulary by filtering only words that have greater than 10 times

In [51]:
token = [key for key in vocab1 if vocab1[key]>10]

In [52]:
token

['test',
 'android',
 'app',
 'beauti',
 'cute',
 'health',
 'iger',
 'iphoneonli',
 'iphonesia',
 'iphon',
 'final',
 'case',
 'thank',
 'yay',
 'soni',
 'xperia',
 'love',
 'would',
 'go',
 'talk',
 'relax',
 'smartphon',
 'wifi',
 'connect',
 'im',
 'know',
 'made',
 'way',
 'home',
 'amaz',
 'servic',
 'appl',
 'wont',
 'even',
 'question',
 'pay',
 'stupid',
 'support',
 'softwar',
 'updat',
 'fuck',
 'phone',
 'big',
 'time',
 'happi',
 'us',
 'instap',
 'instadaili',
 'xperiaz',
 'new',
 'type',
 'c',
 'charger',
 'cabl',
 'uk',
 '…',
 'amazon',
 'year',
 'newyear',
 'start',
 'technolog',
 'samsunggalaxi',
 'iphonex',
 'shop',
 'listen',
 'music',
 'likeforlik',
 'photo',
 'fun',
 'selfi',
 'water',
 'camera',
 'picoftheday',
 'sun',
 'instagood',
 'boy',
 'outdoor',
 'hey',
 'make',
 'ipod',
 'dont',
 'color',
 'inch',
 'crash',
 'everi',
 'need',
 'realli',
 'drop',
 'ball',
 'design',
 'give',
 'anoth',
 'crazi',
 'purchas',
 'lol',
 'work',
 'hard',
 'play',
 'ipad',
 'batteri',
 'charg',
 'dead',
 'saturday',
 'summer',
 'like',
 'share',
 'want',
 'instagram',
 'photooftheday',
 'tweegram',
 'reason',
 'one',
 'suck',
 'truth',
 'agre',
 'fact',
 'store',
 'screen',
 'monday',
 'ur',
 'art',
 'easter',
 'dear',
 'friend',
 'face',
 'email',
 'seem',
 'pie',
 'wife',
 'ive',
 'day',
 'button',
 'back',
 'broke',
 'hit',
 'goe',
 'complet',
 'black',
 'keep',
 'get',
 'text',
 'cant',
 'check',
 'wallpap',
 'wall',
 'galaxi',
 'samsung',
 'patent',
 'million',
 'parti',
 'mess',
 'havent',
 'done',
 'noth',
 'touch',
 'lose',
 'pic',
 'kill',
 'someon',
 'hateappl',
 'flower',
 'green',
 'must',
 'watch',
 'youtub',
 'subscrib',
 'daili',
 'vlog',
 'twitch',
 'game',
 'ps',
 'xbox',
 'io',
 'live',
 'laugh',
 'life',
 'food',
 'instago',
 'instahub',
 'instagram…',
 'friendship',
 'dog',
 'famili',
 'goal',
 'bestfriend',
 'america',
 'taken',
 'sunset',
 'sky',
 'sister',
 'bought',
 'earli',
 'bday',
 'gift',
 'receiv',
 'note',
 'mani',
 'market',
 'delet',
 'song',
 'itun',
 'freak',
 'window',
 'advanc',
 'custom',
 'stand',
 'bad',
 'cheap',
 'tech',
 'bull',
 'smile',
 'creat',
 'let',
 'sunday',
 'alway',
 'eye',
 'ootd',
 'fashion',
 'blackandwhit',
 'film',
 'set',
 'video',
 'produc',
 'follow',
 'movi',
 'act',
 'pink',
 'sweet',
 'sexi',
 'ladi',
 'week',
 'end',
 'iphoneplu',
 'moment',
 'see',
 'differ',
 'photographi',
 'natur',
 'landscap',
 'view',
 'tree',
 'travel',
 'googl',
 'cut',
 'program',
 'look',
 'got',
 'christma',
 'girl',
 'instacool',
 'free',
 'appstor',
 'joy',
 'peac',
 'reflect',
 'rememb',
 'cloud',
 'gr',
 'iphone…',
 'babi',
 'pet',
 'news',
 'fail',
 'funni',
 'hate',
 'tablet',
 'person',
 'use',
 'fan',
 'think',
 'product',
 'friday',
 'call',
 'blackfriday',
 'holiday',
 'newyork',
 'busi',
 'money',
 'birthday',
 'tv',
 'comput',
 'school',
 'serious',
 'month',
 'good',
 'job',
 'actual',
 '£',
 'replac',
 'that',
 'still',
 'rt',
 'droid',
 'cool',
 'pictur',
 'l',
 'run',
 'beach',
 'sport',
 'bit',
 'hashtag',
 'yet',
 'arriv',
 'gain',
 'everyon',
 'sougofollow',
 'ff',
 'iphoneographi',
 'iphonephotographi',
 'mobil',
 'bright',
 'user',
 'date',
 'less',
 'random',
 'instamood',
 'wine',
 'creativ',
 'hot',
 'icon',
 'origin',
 'pop',
 'red',
 'rock',
 'soul',
 'singer',
 'univers',
 'wed',
 'thought',
 'id',
 'lost',
 'ipadmini',
 'feel',
 'broken',
 'light',
 'pleas',
 'indonesia',
 'gold',
 'potd',
 'reset',
 'sorri',
 'white',
 'tea',
 'chill',
 'cover',
 'g',
 'came',
 'magic',
 'come',
 'followsunday',
 'followback',
 'teamfollowback',
 'retweet',
 'ya',
 'thing',
 'i’m',
 'it’',
 'alreadi',
 'problem',
 'issu',
 'abl',
 'sonya',
 'shoot',
 'put',
 'price',
 'devic',
 'win',
 'box',
 'memori',
 'brother',
 '–',
 'oh',
 'lip',
 'enjoy',
 'playstat',
 'gamer',
 'someth',
 'wrong',
 'right',
 'today',
 'earphon',
 'lifestyl',
 'fuckyou',
 'never',
 'bug',
 'littl',
 'qualiti',
 'girlfriend',
 'card',
 'z',
 'present',
 'mom',
 'macbookpro',
 'macbook',
 'quot',
 'word',
 'tweetgram',
 'great',
 'repair',
 'hour',
 'everyth',
 'mode',
 'usa',
 'compani',
 'model',
 'cd',
 'featur',
 'didnt',
 'coffe',
 'effect',
 'spring',
 'galaxynot',
 'special',
 'valentin',
 'nowplay',
 'daughter',
 'poem',
 'car',
 'sign',
 'lunch',
 'park',
 'banana',
 'autumn',
 'spend',
 'much',
 'book',
 'say',
 'u',
 'took',
 'download',
 'ad',
 'twitter',
 'educ',
 'n',
 'miss',
 'last',
 'min',
 'tmobil',
 'rid',
 'absolut',
 'annoy',
 'level',
 'buy',
 'full',
 'version',
 'import',
 'mood',
 'blog',
 'style',
 'bestoftheday',
 'pretti',
 'babe',
 'send',
 'turn',
 'imessag',
 'sleep',
 'popular',
 'tweet',
 'shotoniphon',
 'photograph',
 'sync',
 'second',
 'fml',
 'candi',
 'nice',
 'wait',
 'hand',
 'gb',
 'first',
 'bar',
 'key',
 'long',
 'cold',
 'boot',
 'siri',
 'doesnt',
 'liter',
 'cri',
 'contact',
 'wonder',
 'avail',
 'b',
 'laptop',
 'vaio',
 'blackberri',
 'best',
 'fruit',
 'fall',
 'soon',
 'yum',
 'mac',
 'display',
 'told',
 'stop',
 'p',
 'three',
 'ship',
 'gear',
 'well',
 'past',
 'singl',
 'capetownsup',
 'sup',
 'surf',
 'capetown',
 'pro',
 'half',
 'stuff',
 'excit',
 'open',
 'mine',
 'piss',
 'offici',
 'keyboard',
 'okay',
 'though',
 'enough',
 'simpl',
 'th',
 'refus',
 'night',
 'son',
 'instagood…',
 'jj',
 'makeup',
 'valentinesday',
 'februari',
 'portrait',
 'shot',
 'sonyalpha',
 'mm',
 'password',
 'zoom',
 'stevejob',
 'yall',
 'addict',
 'prophet',
 'husband',
 'kindl',
 'a…',
 'upgrad',
 'help',
 'children',
 'there',
 'least',
 'tab',
 'real',
 'visit',
 'hi',
 'world',
 'old',
 'followm',
 'likelik',
 'samsung…',
 'swag',
 'cat',
 'edit',
 'sick',
 'paint',
 'bullshit',
 'may',
 'perfect',
 'instaphoto',
 'welcom',
 'draw',
 'os',
 'throw',
 'fast',
 'w',
 'take',
 'two',
 'next',
 'offer',
 'middl',
 'access',
 'account',
 'find',
 'citi',
 'stori',
 'destini',
 'awesom',
 'accessori',
 'info',
 'goodnight',
 'dream',
 'hope',
 'uae',
 'lucki',
 'deal',
 'passion',
 'read',
 'edm',
 'whole',
 'playlist',
 'god',
 'nx',
 'cuti',
 'high',
 'usb',
 'geek',
 'bot',
 'gadget',
 'power',
 'pc',
 'sprint',
 'pick',
 'wish',
 'minut',
 'count',
 'tl',
 'drive',
 'nyc',
 'gay',
 'readi',
 'cellphon',
 'space',
 'ny',
 'tattoo',
 'total',
 'ye',
 'via',
 'air',
 'instal',
 'fit',
 'plu',
 'sim',
 'florida',
 'sale',
 'nokia',
 'motorola',
 'lg',
 'without',
 'hold',
 'speed',
 'unitedst',
 'guitarplay',
 'smart',
 'crap',
 'calendar',
 'event',
 'icloud',
 'angri',
 'bird',
 'freez',
 'ever',
 'sinc',
 'team',
 'tri',
 'convers',
 'wouldnt',
 'small',
 'blue',
 '—',
 'steemit',
 'sonylen',
 'len',
 'sonyphotographi',
 'imag',
 'photofe',
 'feed',
 'yeah',
 'gorgeou',
 'ig',
 'orang',
 'haha',
 'dress',
 'lock',
 'speaker',
 'reallyr',
 'colleg',
 'true',
 'chocol',
 'shit',
 'ador',
 'nofilt',
 'drink',
 'purpl',
 'tasti',
 'garden',
 'андроид',
 'guy',
 'bestpric',
 'jun',
 'unlock',
 'caus',
 'manag',
 'mommi',
 'bless',
 'could',
 'chines',
 'close',
 'system',
 'morn',
 'nike',
 'goodmorn',
 'r',
 'imac',
 'sell',
 'mad',
 'purpos',
 'pari',
 'answer',
 'roll',
 'verizon',
 'headphon',
 'show',
 'sound',
 'itali',
 'socialmedia',
 'learn',
 'smoke',
 'tomorrow',
 'here',
 'delici',
 'far',
 'away',
 'ebay',
 'fix',
 'easi',
 'silver',
 'oneplu',
 'provid',
 'experi',
 'flag',
 'emoji',
 'chang',
 'al',
 'april',
 'man',
 'wanna',
 'your',
 'tell',
 'kid',
 'backup',
 'peopl',
 'dad',
 'anyon',
 'els',
 'block',
 'number',
 'possibl',
 'frustrat',
 'file',
 'bro',
 'rhyme',
 'thx',
 'jailbreak',
 'sit',
 'restor',
 'stock',
 'mother',
 'igdaili',
 'marri',
 'healthi',
 'ugh',
 'x',
 'bc',
 'gratitud',
 'edg',
 'unbox',
 'wow',
 'sonyphoto',
 'top',
 'phonecas',
 'june',
 'sad',
 'yellow',
 'woman',
 'might',
 'india',
 'canada',
 'europ',
 'super',
 'care',
 'map',
 'applestor',
 'hello',
 'order',
 'sent',
 'went',
 'wasnt',
 'insta',
 'newphon',
 'fish',
 'london',
 'vsco',
 'track',
 'catch',
 'finger',
 'anymor',
 'captur',
 'futur',
 'cell',
 'instalik',
 'sony…',
 'march',
 'proud',
 'hateiphon',
 'sticker',
 'vscocam',
 'bring',
 'better',
 'kiss',
 'heart',
 'fresh',
 'librari',
 'inspir',
 'inlov',
 'luxuri',
 'exquisit',
 'squishi',
 'charm',
 'strap',
 'toy',
 'decor',
 'cake',
 'theyr',
 'lte',
 'facebook',
 'wipe',
 'human',
 'bff',
 'instalov',
 'storag',
 'wake',
 'shitti',
 'wast',
 'switch',
 'blond',
 'load',
 'sue',
 'teamandroid',
 'da',
 'ly',
 'lion',
 'steve',
 'also',
 'ill',
 'osx',
 'photoshoot',
 'coupl',
 'favorit',
 'forc',
 'newtoy',
 'nascar',
 'tire',
 'appar',
 'ago',
 'zeeland',
 'appletv',
 'ask',
 'said',
 'meet',
 'electron',
 'gener',
 'link',
 'code',
 'tshirt',
 'tbt',
 'beat',
 'screw',
 'videogam',
 'motiv',
 'sunni',
 'nikon',
 'useless',
 'boyfriend',
 'weekend',
 'cook',
 'japan',
 'starbuck',
 'almost',
 'cousin',
 'tag',
 'applesuck',
 'bye',
 'search',
 'dinner',
 'discount',
 'cheer',
 'bluetooth',
 'wireless',
 'data',
 'spent',
 'puppi',
 'vacat',
 'anim',
 'notebook',
 'redbubbl',
 'iphonecas',
 'king',
 'yo',
 'left',
 'mean',
 'what',
 'yesterday',
 'mayb',
 'trump',
 'california',
 'repost',
 'samsungmobil',
 'gone',
 'social',
 'break',
 'trip',
 'slow',
 'rain',
 'wtf',
 'anyth',
 'cuz',
 'hd',
 'microsoft',
 'applewatch',
 'duo',
 'dj',
 'save',
 'mr',
 'releas',
 'gonna',
 'entir',
 'part',
 'die',
 'k',
 'tip',
 'gotta',
 'eat',
 'walk',
 'side',
 'explor',
 'hous',
 'room',
 'rs',
 'piano',
 'v',
 'thankyou',
 'happen',
 'page',
 'surpris',
 'deliveri',
 'messag',
 'vocat',
 'thailand',
 'khaoko',
 'ilc',
 'snapspeed…',
 'merri',
 'htc',
 'onlin',
 'psn',
 'flash',
 '•',
 'treat',
 'tagsforlik',
 'cost',
 'crack',
 'collect',
 'stuck',
 'planet',
 'men',
 'followfollow',
 'blow',
 'latest',
 'consol',
 'blogger',
 'protect',
 'skin',
 'choos',
 'uniqu',
 'piec',
 'lot',
 'remov',
 'secur',
 'princess',
 'mind',
 'becom',
 'miami',
 'nail',
 'rip',
 'figur',
 'network',
 'bitch',
 'tuesday',
 'f',
 'idea',
 'fb',
 'omg',
 'innov',
 'player',
 'forev',
 'satisfi',
 'tonight',
 'artist',
 'sing',
 'click',
 'hair',
 'ride',
 'leav',
 'colour',
 'togeth',
 'asshol',
 ...]

In [53]:
len(token)

1145

Now it narrow until 1145. if there are more features that model can be overfitt. when trainning accurcy of the model is over accurate than testing accuracy that model is overfitted. some times this number also can be large.

this token is the our vocabulary. And it wants to feature trainnigs. so we save it as a text file

In [55]:
def save_vocabulary(lines,filename):
    data = '\n'.join(lines)
    file = open(filename,'w',encoding="utf-8")
    file.write(data)
    file.close()

save_vocabulary(token,'../static/model/vocabulary.txt')

##Divide Dataset - for trainnig and testing##

In [56]:
data

        id  label                                              tweet
0        1      0  fingerprint pregnanc test android app beauti c...
1        2      0  final transpar silicon case thank uncl yay son...
2        3      0  love would go talk makememori unplug relax iph...
3        4      0  im wire know im georg made way iphon cute dave...
4        5      1  amaz servic appl wont even talk question unles...
...    ...    ...                                                ...
7915  7916      0  live loud lol liveoutloud selfi smile soni mus...
7916  7917      0  would like wish amaz day make everi minut coun...
7917  7918      0  help love year old neighbor ipad morn made rea...
7918  7919      0  final got smart pocket wifi stay connect anyti...
7919  7920      0  appl barcelona appl store bcn barcelona travel...

[7920 rows x 3 columns]

In [60]:
x = data['tweet']
y = data['label']

In [58]:
x

0       fingerprint pregnanc test android app beauti c...
1       final transpar silicon case thank uncl yay son...
2       love would go talk makememori unplug relax iph...
3       im wire know im georg made way iphon cute dave...
4       amaz servic appl wont even talk question unles...
                              ...
7915    live loud lol liveoutloud selfi smile soni mus...
7916    would like wish amaz day make everi minut coun...
7917    help love year old neighbor ipad morn made rea...
7918    final got smart pocket wifi stay connect anyti...
7919    appl barcelona appl store bcn barcelona travel...
Name: tweet, Length: 7920, dtype: str

In [61]:
y

0       0
1       0
2       0
3       0
4       1
       ..
7915    0
7916    0
7917    0
7918    0
7919    0
Name: label, Length: 7920, dtype: int64

In [62]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from scikit-learn) (2.4.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from scikit-learn) (1.5.3)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 672.2 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/8.0 MB 672.2 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/8.0 MB 672.2 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/8.0 MB 672.2 kB/s eta 0:00:12
   --- ------------------------------------ 0.8/8.0 MB 453.5 kB/s eta 0:00:16
   --- ------------------------------------ 0.8/8.0 MB 453.5 kB/s eta 0:00:16
   ----- ---------------------------------- 1.0/8.0 MB 488.8 kB/s eta 0:00:15
   ----- ---------------------------------- 1.0/8.0 MB 488.8 kB/s eta 0:00:15
   ------ --------------------------------- 1.3/8.0 MB 524.3 kB/s eta 0:00:13
   ------ --------------------------------- 1.3/8.0 MB 524.3 kB/s eta 0:00:13
   ------- -------------------------------- 1.6/8.0 MB 524.3 kB/s eta 0:00:13
   ------- -------------------------------- 1.6/8.0 MB 524.3 kB/s eta 0:00:13
   --------- ------------------------------ 1.8/8.0 MB 521.7 kB/s eta 0:00:12
   --------- ------------------------------ 1.8/8.0 MB 521.7 kB/s eta 0:00:12
   ---------- ----------------------------- 2.1/8.0 MB 556.6 kB/s eta 0:00:11
   ----------- ---------------------------- 2.4/8.0 MB 604.5 kB/s eta 0:00:10
   ----------- ---------------------------- 2.4/8.0 MB 604.5 kB/s eta 0:00:10
   ------------- -------------------------- 2.6/8.0 MB 606.5 kB/s eta 0:00:09
   -------------- ------------------------- 2.9/8.0 MB 628.3 kB/s eta 0:00:09
   -------------- ------------------------- 2.9/8.0 MB 628.3 kB/s eta 0:00:09
   --------------- ------------------------ 3.1/8.0 MB 619.3 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.0 MB 619.3 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.0 MB 619.3 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.0 MB 595.7 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.0 MB 595.7 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.0 MB 595.7 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.0 MB 586.4 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.0 MB 586.4 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.0 MB 586.4 kB/s eta 0:00:08
   ------------------- -------------------- 3.9/8.0 MB 560.6 kB/s eta 0:00:08
   ------------------- -------------------- 3.9/8.0 MB 560.6 kB/s eta 0:00:08
   ------------------- -------------------- 3.9/8.0 MB 560.6 kB/s eta 0:00:08
   ------------------- -------------------- 3.9/8.0 MB 560.6 kB/s eta 0:00:08
   -------------------- ------------------- 4.2/8.0 MB 535.4 kB/s eta 0:00:08
   -------------------- ------------------- 4.2/8.0 MB 535.4 kB/s eta 0:00:08
   -------------------- ------------------- 4.2/8.0 MB 535.4 kB/s eta 0:00:08
   -------------------- ------------------- 4.2/8.0 MB 535.4 kB/s eta 0:00:08
   ---------------------- ----------------- 4.5/8.0 MB 507.5 kB/s eta 0:00:08
   ---------------------- ----------------- 4.5/8.0 MB 507.5 kB/s eta 0:00:08
   ---------------------- ----------------- 4.5/8.0 MB 507.5 kB/s eta 0:00:08
   ---------------------- ----------------- 4.5/8.0 MB 507.5 kB/s eta 0:00:08
   ---------------------- ----------------- 4.5/8.0 MB 507.5 kB/s eta 0:00:08
   ----------------------- ---------------- 4.7/8.0 MB 485.1 kB/s eta 0:00:07
   ----------------------- ---------------- 4.7/8.0 MB 485.1 kB/s eta 0:00:07
   ------------------------ --------------- 5.0/8.0 MB 480.9 kB/s eta 0:00:07
   ------------------------ --------------- 5.0/8.0 MB 480.9 kB/s eta 0:00:07
   ------------------------ --------------- 5.0/8.0 MB 480.9 kB/s eta 0:00:07
   -------------------------- ------------- 5.2/8.0 MB 479.4 kB/s eta 0:00:06
   -------------------------- ------------- 5.2/8.0 MB 479.4 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.0 MB 483.5 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.0 MB 483.5 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.0 MB 483.5 kB/s eta 0:00:06
   ---------------------------- ----------- 5.8/8.0 MB 484.6 kB/s eta 0:00:05
   ---------------------------- ----------- 5.8/8.0 MB 484.6 kB/s eta 0:00:05
   ------------------------------ --------- 6.0/8.0 MB 488.9 kB/s eta 0:00:05
   ------------------------------ --------- 6.0/8.0 MB 488.9 kB/s eta 0:00:05
   ------------------------------- -------- 6.3/8.0 MB 492.8 kB/s eta 0:00:04
   ------------------------------- -------- 6.3/8.0 MB 492.8 kB/s eta 0:00:04
   ------------------------------- -------- 6.3/8.0 MB 492.8 kB/s eta 0:00:04
   -------------------------------- ------- 6.6/8.0 MB 494.1 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.0 MB 494.1 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.0 MB 497.0 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.0 MB 497.0 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.0 MB 497.0 kB/s eta 0:00:03
   ----------------------------------- ---- 7.1/8.0 MB 494.0 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.0 MB 494.0 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 494.0 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 494.0 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.0 MB 496.0 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 496.0 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 496.0 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 499.0 kB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 502.0 kB/s  0:00:15
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
    --------------------------------------- 0.5/36.5 MB 598.5 kB/s eta 0:01:01
    --------------------------------------- 0.8/36.5 MB 633.2 kB/s eta 0:00:57
    --------------------------------------- 0.8/36.5 MB 633.2 kB/s eta 0:00:57
   - -------------------------------------- 1.0/36.5 MB 671.0 kB/s eta 0:00:53
   - -------------------------------------- 1.3/36.5 MB 706.6 kB/s eta 0:00:50
   - -------------------------------------- 1.3/36.5 MB 706.6 kB/s eta 0:00:50
   - -------------------------------------- 1.6/36.5 MB 682.0 kB/s eta 0:00:52
   -- ------------------------------------- 1.8/36.5 MB 718.9 kB/s eta 0:00:49
   -- ------------------------------------- 2.1/36.5 MB 793.3 kB/s eta 0:00:44
   -- ------------------------------------- 2.6/36.5 MB 883.0 kB/s eta 0:00:39
   --- ------------------------------------ 2.9/36.5 MB 927.0 kB/s eta 0:00:37
   --- ------------------------------------ 3.1/36.5 MB 956.1 kB/s eta 0:00:35
   --- ------------------------------------ 3.1/36.5 MB 956.1 kB/s eta 0:00:35
   --- ------------------------------------ 3.1/36.5 MB 956.1 kB/s eta 0:00:35
   --- ------------------------------------ 3.1/36.5 MB 956.1 kB/s eta 0:00:35
   --- ------------------------------------ 3.1/36.5 MB 956.1 kB/s eta 0:00:35
   --- ------------------------------------ 3.1/36.5 MB 956.1 kB/s eta 0:00:35
   --- ------------------------------------ 3.1/36.5 MB 956.1 kB/s eta 0:00:35
   --- ------------------------------------ 3.1/36.5 MB 956.1 kB/s eta 0:00:35
   --- ------------------------------------ 3.4/36.5 MB 671.0 kB/s eta 0:00:50
   ---- ----------------------------------- 3.9/36.5 MB 738.6 kB/s eta 0:00:45
   ---- ----------------------------------- 4.5/36.5 MB 808.5 kB/s eta 0:00:40
   ----- ---------------------------------- 5.0/36.5 MB 880.5 kB/s eta 0:00:36
   ------ --------------------------------- 5.5/36.5 MB 932.1 kB/s eta 0:00:34
   ------ --------------------------------- 6.0/36.5 MB 989.6 kB/s eta 0:00:31
   ------- -------------------------------- 6.6/36.5 MB 1.0 MB/s eta 0:00:29
   ------- -------------------------------- 6.8/36.5 MB 1.1 MB/s eta 0:00:28
   ------- -------------------------------- 6.8/36.5 MB 1.1 MB/s eta 0:00:28
   -------- ------------------------------- 7.3/36.5 MB 1.1 MB/s eta 0:00:28
   -------- ------------------------------- 7.9/36.5 MB 1.1 MB/s eta 0:00:26
   --------- ------------------------------ 8.4/36.5 MB 1.2 MB/s eta 0:00:25
   --------- ------------------------------ 8.7/36.5 MB 1.2 MB/s eta 0:00:24
   --------- ------------------------------ 8.7/36.5 MB 1.2 MB/s eta 0:00:24
   ---------- ----------------------------- 9.2/36.5 MB 1.2 MB/s eta 0:00:24
   ---------- ----------------------------- 10.0/36.5 MB 1.2 MB/s eta 0:00:22
   ----------- ---------------------------- 10.5/36.5 MB 1.3 MB/s eta 0:00:21
   ----------- ---------------------------- 10.5/36.5 MB 1.3 MB/s eta 0:00:21
   ----------- ---------------------------- 10.7/36.5 MB 1.2 MB/s eta 0:00:21
   ------------ --------------------------- 11.3/36.5 MB 1.3 MB/s eta 0:00:20
   ------------- -------------------------- 12.1/36.5 MB 1.3 MB/s eta 0:00:19
   ------------- -------------------------- 12.3/36.5 MB 1.3 MB/s eta 0:00:19
   ------------- -------------------------- 12.3/36.5 MB 1.3 MB/s eta 0:00:19
   -------------- ------------------------- 12.8/36.5 MB 1.3 MB/s eta 0:00:19
   -------------- ------------------------- 13.6/36.5 MB 1.4 MB/s eta 0:00:17
   --------------- ------------------------ 13.9/36.5 MB 1.4 MB/s eta 0:00:17
   --------------- ------------------------ 14.2/36.5 MB 1.4 MB/s eta 0:00:17
   --------------- ------------------------ 14.4/36.5 MB 1.3 MB/s eta 0:00:17
   ---------------- ----------------------- 14.9/36.5 MB 1.4 MB/s eta 0:00:16
   ---------------- ----------------------- 15.5/36.5 MB 1.4 MB/s eta 0:00:16
   ----------------- ---------------------- 16.0/36.5 MB 1.4 MB/s eta 0:00:15
   ----------------- ---------------------- 16.0/36.5 MB 1.4 MB/s eta 0:00:15
   ----------------- ---------------------- 16.3/36.5 MB 1.4 MB/s eta 0:00:15
   ------------------ --------------------- 17.0/36.5 MB 1.4 MB/s eta 0:00:14
   ------------------- -------------------- 17.6/36.5 MB 1.4 MB/s eta 0:00:14
   ------------------- -------------------- 17.8/36.5 MB 1.5 MB/s eta 0:00:13
   ------------------- -------------------- 17.8/36.5 MB 1.5 MB/s eta 0:00:13
   -------------------- ------------------- 18.4/36.5 MB 1.4 MB/s eta 0:00:13
   -------------------- ------------------- 18.9/36.5 MB 1.5 MB/s eta 0:00:13
   --------------------- ------------------ 19.4/36.5 MB 1.5 MB/s eta 0:00:12
   --------------------- ------------------ 19.9/36.5 MB 1.5 MB/s eta 0:00:12
   --------------------- ------------------ 19.9/36.5 MB 1.5 MB/s eta 0:00:12
   ---------------------- ----------------- 20.4/36.5 MB 1.5 MB/s eta 0:00:11
   ---------------------- ----------------- 21.0/36.5 MB 1.5 MB/s eta 0:00:11
   ----------------------- ---------------- 21.5/36.5 MB 1.5 MB/s eta 0:00:10
   ----------------------- ---------------- 21.8/36.5 MB 1.5 MB/s eta 0:00:10
   ----------------------- ---------------- 21.8/36.5 MB 1.5 MB/s eta 0:00:10
   ------------------------ --------------- 22.3/36.5 MB 1.5 MB/s eta 0:00:10
   ------------------------- -------------- 23.1/36.5 MB 1.5 MB/s eta 0:00:09
   ------------------------- -------------- 23.3/36.5 MB 1.5 MB/s eta 0:00:09
   ------------------------- -------------- 23.6/36.5 MB 1.5 MB/s eta 0:00:09
   ------------------------- -------------- 23.6/36.5 MB 1.5 MB/s eta 0:00:09
   -------------------------- ------------- 24.4/36.5 MB 1.5 MB/s eta 0:00:08
   --------------------------- ------------ 24.9/36.5 MB 1.5 MB/s eta 0:00:08
   --------------------------- ------------ 25.4/36.5 MB 1.6 MB/s eta 0:00:08
   --------------------------- ------------ 25.4/36.5 MB 1.6 MB/s eta 0:00:08
   --------------------------- ------------ 25.4/36.5 MB 1.6 MB/s eta 0:00:08
   ---------------------------- ----------- 26.2/36.5 MB 1.5 MB/s eta 0:00:07
   ----------------------------- ---------- 26.7/36.5 MB 1.6 MB/s eta 0:00:07
   ----------------------------- ---------- 27.3/36.5 MB 1.6 MB/s eta 0:00:06
   ----------------------------- ---------- 27.3/36.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 27.5/36.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 27.8/36.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 28.6/36.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 29.1/36.5 MB 1.6 MB/s eta 0:00:05
   ------------------------------- -------- 29.1/36.5 MB 1.6 MB/s eta 0:00:05
   -------------------------------- ------- 29.4/36.5 MB 1.6 MB/s eta 0:00:05
   -------------------------------- ------- 30.1/36.5 MB 1.6 MB/s eta 0:00:05
   --------------------------------- ------ 30.9/36.5 MB 1.6 MB/s eta 0:00:04
   --------------------------------- ------ 30.9/36.5 MB 1.6 MB/s eta 0:00:04
   --------------------------------- ------ 30.9/36.5 MB 1.6 MB/s eta 0:00:04
   ---------------------------------- ----- 31.5/36.5 MB 1.6 MB/s eta 0:00:04
   ----------------------------------- ---- 32.2/36.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 32.8/36.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 32.8/36.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 32.8/36.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------------ --- 33.3/36.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------------- -- 33.8/36.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 34.6/36.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 34.6/36.5 MB 1.6 MB/s eta 0:00:02
   -------------------------------------- - 34.9/36.5 MB 1.6 MB/s eta 0:00:02
   -------------------------------------- - 35.4/36.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 1.6 MB/s  0:00:22
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, scikit-learn

   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]

we divide the data set to 20% to testing and rest for trainning

In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [66]:
x_train.shape

(6336,)

In [67]:
x_test.shape

(1584,)

In [68]:
y_train

3469    0
7789    0
6625    0
1663    1
997     0
       ..
750     0
6472    0
5149    0
6058    0
7039    0
Name: label, Length: 6336, dtype: int64

In [69]:
x_train

3469    care home put girl through… news photographi f...
7789         itun let add music librari appl someonefixit
6625    check origin vintag macdraw pro book clari mac...
1663    man fuckyou appl came symbol first theplung we...
997     slowhand drbanana widget see twitter stock wea...
                              ...
750     gain follow rt must follow follow back follow ...
6472    didyouknow appl air float water yummi nomnomno...
5149    would like wish amaz day make everi minut coun...
6058    yesi girl mybestfriend adventur hunt beauti fu...
7039    new iphon iphon plu appl io iphon news iphonex...
Name: tweet, Length: 6336, dtype: str

In [70]:
x_test

5487    amaz app love … photographi nowplay girl quot ...
5830    bath heat hot motorola razr new good like sexi...
3457    order appl cinema display whoopwhoop jump danc...
4373    anybodi listen new u yet took night convinc it...
4648    follow capetownsup instagram sup surf fun cape...
                              ...
3876    like case transpar soft tpu case iphon x plu s...
4243    risen version angel fire still progress friday...
4494    gt bluetooth smartwatch smart watch sim card s...
4189    iphon cabl drive crazi want cut piec appl char...
3617    new phone im happi grate mom soni pictwitterco...
Name: tweet, Length: 1584, dtype: str

we have vectorized the x_train and x_test

##Vectorization##

In [75]:
def vectorizer(ds, vocabulary):
    vectorized_lst = []
    
    for sentence in ds:
        sentence_lst = np.zeros(len(vocabulary))

        for i in range(len(vocabulary)):
            if vocabulary[i] in sentence.split():
                sentence_lst[i] = 1

        vectorized_lst.append(sentence_lst)

    vectorized_lst_new = np.asarray(vectorized_lst, dtype=np.float32)

    return vectorized_lst_new

In [76]:
vectorized_x_train = vectorizer(x_train,token)

In [77]:
vectorized_x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(6336, 1145), dtype=float32)

In [78]:
for i in vectorized_x_train[0]:
    print(i)

0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [79]:
vectorized_x_test = vectorizer(x_test,token)

In [80]:
vectorized_x_test

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1584, 1145), dtype=float32)

In [81]:
y_train.value_counts()

label
0    4721
1    1615
Name: count, dtype: int64

in this dataset has lot of 0 values than 1s. Therefore this can be imbalanced dataset. if the dataset imbalanced model biased to predict 0s.

###Handling Imblanced dataset##
we handle only trainning dataset only

In [82]:
!pip install imbalanced-learn

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from imbalanced-learn) (2.4.2)
Requirement already satisfied: scipy<2,>=1.11.4 in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in C:\Users\DELL\Desktop\sentiment_analysis_project\env\Lib\site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   ---------------------------------------- 0/2 [sklearn-compat]
   ---------------------------------------- 0/2 [sklearn-compat]
   ---------------------------------------- 0/2 [sklearn-compat]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.1 sklearn-compat-0.1.5

In [86]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
vectorized_x_train_smote, y_train_smote = smote.fit_resample(vectorized_x_train,y_train)
print(vectorized_x_train_smote.shape,y_train_smote.shape)

(9442, 1145) (9442,)

In [87]:
y_train_smote.value_counts()

label
0    4721
1    4721
Name: count, dtype: int64

Now it is balanced

For trainning - vectorized_x_train_smote
                y_train_smote

For testing -  vectorized_x_test
                y_test

###Model Trainning###

In [89]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [90]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

def training_scores(y_act, y_pred):
    acc = round(accuracy_score(y_act, y_pred), 3)
    pr = round(precision_score(y_act, y_pred), 3)
    rec = round(recall_score(y_act, y_pred), 3)
    f1 = round(f1_score(y_act, y_pred), 3)
    print(f'Training Scores:\n\tAccuracy = {acc}\n\tPrecision = {pr}\n\tRecall = {rec}\n\tF1-Score = {f1}')

def validation_scores(y_act, y_pred):
    acc = round(accuracy_score(y_act, y_pred), 3)
    pr = round(precision_score(y_act, y_pred), 3)
    rec = round(recall_score(y_act, y_pred), 3)
    f1 = round(f1_score(y_act, y_pred), 3)
    print(f'Testing Scores:\n\tAccuracy = {acc}\n\tPrecision = {pr}\n\tRecall = {rec}\n\tF1-Score = {f1}')

##Logistic Regression

In [100]:
lr = LogisticRegression()
lr.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = lr.predict(vectorized_x_train_smote)

y_test_pred = lr.predict(vectorized_x_test)

training_scores(y_train_smote,y_train_pred)

validation_scores(y_test,y_test_pred)

Training Scores:
	Accuracy = 0.938
	Precision = 0.915
	Recall = 0.965
	F1-Score = 0.94
Testing Scores:
	Accuracy = 0.877
	Precision = 0.723
	Recall = 0.852
	F1-Score = 0.782

##Naive Base##

In [101]:
mnb = MultinomialNB()
mnb.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = mnb.predict(vectorized_x_train_smote)

y_test_pred = mnb.predict(vectorized_x_test)

training_scores(y_train_smote,y_train_pred)

validation_scores(y_test,y_test_pred)

Training Scores:
	Accuracy = 0.905
	Precision = 0.868
	Recall = 0.956
	F1-Score = 0.91
Testing Scores:
	Accuracy = 0.876
	Precision = 0.695
	Recall = 0.927
	F1-Score = 0.795

##DecisionTree##

In [102]:
dt = DecisionTreeClassifier()
dt.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = dt.predict(vectorized_x_train_smote)

y_test_pred = dt.predict(vectorized_x_test)

training_scores(y_train_smote,y_train_pred)

validation_scores(y_test,y_test_pred)

Training Scores:
	Accuracy = 1.0
	Precision = 1.0
	Recall = 1.0
	F1-Score = 1.0
Testing Scores:
	Accuracy = 0.83
	Precision = 0.689
	Recall = 0.63
	F1-Score = 0.658

dataset may be overfitted , therefore become 1 for accuracy

##Random Forest Classifier##

In [104]:
rfc = RandomForestClassifier()
rfc.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = rfc.predict(vectorized_x_train_smote)

y_test_pred = rfc.predict(vectorized_x_test)

training_scores(y_train_smote,y_train_pred)

validation_scores(y_test,y_test_pred)

Training Scores:
	Accuracy = 1.0
	Precision = 1.0
	Recall = 1.0
	F1-Score = 1.0
Testing Scores:
	Accuracy = 0.869
	Precision = 0.772
	Recall = 0.701
	F1-Score = 0.735

In [105]:
svc = SVC()
svc.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = svc.predict(vectorized_x_train_smote)

y_test_pred = svc.predict(vectorized_x_test)

training_scores(y_train_smote,y_train_pred)

validation_scores(y_test,y_test_pred)

Training Scores:
	Accuracy = 0.979
	Precision = 0.963
	Recall = 0.996
	F1-Score = 0.979
Testing Scores:
	Accuracy = 0.884
	Precision = 0.754
	Recall = 0.82
	F1-Score = 0.786

In [107]:
import pickle
with open('../static/model/model.pickle','wb') as file:
    pickle.dump(lr,file)